### ISSUE TITLE
Deluge not starting when using vpn

### ISSUE THREAD

**Issue by daniel-van-niekerk** [GreenFrogSB/LMDS#22]
I've got the vpn container set up but the Deluge container doesn't start. I can start it manually in Portainer and then it works fine.
My docker-compose for deluge looks like this:

```
deluge:
    image: linuxserver/deluge
    container_name: deluge
    depends_on:     # Add dependency on vpn container, this container wont start if vpn container is not running.
      - vpn
    network_mode: service:vpn
    # network_mode: host
    environment:
      - PUID=0
      - PGID=0
      - TZ=UTC
      - UMASK=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ./volumes/deluge/config:/config
      - ./downloads:/downloads
    restart: unless-stopped
```

I added the restart: unless-stopped but it doesn't make a difference.

I noticed that the vpn container takes about 1 minute to start up. It starting for a while and then goes to Healthy instead of running. Hovering over the label says that this container has a health check.
Not sure if Deluge is not starting because it takes long for the vpn to start or because the vpn eventually shows Healthy instead of Running. I'm not very good with docker unfortunately.

If it helps this is the log of the Deluge container after a reboot:

```
KeyError: ('RPCServer',)

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] sending all processes the TERM signal.

[s6-finish] sending all processes the KILL signal and exiting.
```

Do you have any idea what the issue might be?
