### ISSUE TITLE
changes saved to docker-compose.yml are being reverted by docker-compose

### ISSUE THREAD

**Issue by chenks** [GreenFrogSB/LMDS#54]
i have an issue manually making changes to the `docker-compose.yml` file
any time i go in and manually change the `TZ` from `UTC` to `Europe/London` or manually change any of the volumes mountings, saving the changes correctly saves the changes to the file.

however, after running `docker-compose up -d` it seems to revert all my changes back to default.

for example, i changed the sonarr entry to this

```
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - ./volumes/sonarr/data:/config
      - ./home/chenks/LMDS/media:/tv
      - ./home/chenks/LMDS/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
```

saved the changes, ran the docker command, and it had reverted it back to 

 ```
 sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - UMASK_SET=022 #optional
    volumes:
      - ./volumes/sonarr/data:/config
      - ./media/tvshows:/tv
      - ./downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
```

why are my changes being reverted?
is it possible i'm making too many changes at once?
